FROM node:16

WORKDIR /app

# Копируем package.json и устанавливаем зависимости
COPY frontend/package.json ./
RUN npm install

# Копируем весь проект (включая public/ и src/)
COPY frontend/ .

# Собираем приложение
RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]