FROM python:3.9-slim

WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем app.py
COPY backend/app.py .

# Создаём папку для данных
RUN mkdir -p /app/data

# Копируем CSV файлы
COPY recommender/models/movies.csv /app/data/
COPY recommender/data/logs.csv /app/data/
COPY recommender/data/genres.csv /app/data/
COPY recommender/data/countries.csv /app/data/
COPY recommender/data/staff.csv /app/data/

EXPOSE 5001

CMD ["python", "app.py"]
