version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - DATABASE_HOST=db
      - RECOMMENDER_URL=http://recommender:5000
    depends_on:
      - db
      - recommender

  recommender:
    build:
      context: .
      dockerfile: Dockerfile.recommender
    ports:
      - "5000:5000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: